#!/bin/sh
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from ARM Limited
# (C) COPYRIGHT 2011 ARM Limited
# ALL RIGHTS RESERVED
# The entire notice above must be reproduced on all authorised
# copies and copies may only be made to the extent permitted
# by a licensing agreement from ARM Limited.

# This script wraps calls to armar. If it is called with just one
# argument, i.e. it is creating an archive but with no contents,
# an empty archive is manually created.  This is to provide compatibility
# with GNU ar, as armar does not create empty archives while GNU ar does.

FIRST="-$1"
shift
armar "$FIRST" "$@"
if [ $# -eq 1 ]
then
	echo "!<arch>" > "$1"
fi
